[maintainer]
name = "Zheng Yang"
email = "" # Optional, but good to have if you want

[project]
id = "screenwriter"
name = "Screenwriter"
tagline = "Screenplay formatting and syncing tools for Blender."
maintainer = "Zheng Yang"
license = "SPDX:GPL-3.0-or-later"
version = "1.0.0"
type = "add-on"
blender_version_min = "4.0.0"
platforms = ["windows-x64", "macos-arm64", "macos-x64", "linux-x64"]

[url]
website = "https://github.com/yangster237/Blender-Screenwriter"
source = "https://github.com/yangster237/Blender-Screenwriter"

[permissions]
files = "Reading and writing .fountain files"
network = "No network access required"
clipboard = "No clipboard access required"

[build]
paths_exclude_pattern = [
    "__pycache__/*",
    "*.pyc",
    ".git/*",
    ".vscode/*"
]
