schema_version = "1.0.0"

id = "screenwriter"
version = "1.0.0"
name = "Screenwriter"
tagline = "Screenplay formatting and syncing tools for Blender."
maintainer = "Zheng Yang"
type = "add-on"
license = "SPDX:GPL-3.0-or-later"
website = "https://github.com/yangster237/Blender-Screenwriter"

[blender]
version_min = "4.0.0"

[permissions]
files = "Reading and writing .fountain files"
# Network and clipboard not needed, so omitting them is cleaner or we can leave optional

[build]
paths_exclude_pattern = [
    "__pycache__/*",
    "*.pyc",
    ".git/*",
    ".vscode/*"
]
